### PR TITLE
Allow to select plugin on startup

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by Fobhep** [comment]
this needs a rebase ;)

**Review by Fobhep — CHANGES_REQUESTED** [review]
Nice feature
It would be perfect if you could offer a dynamic list of all avaiblable plugins on an output command like:
sop --plugin-list or similar

**Comment by mdellweg** [comment]
@Fobhep ping

**Review by Fobhep — APPROVED** [review]

**Comment by Fobhep** [comment]
@mdellweg LGTM. however I will still test it before merging

**Review by Fobhep — CHANGES_REQUESTED** [review]
please make sure it is clear for the user that only the suffix of the plugin i.e. thre "real" plugin name is needed with the -p flag.
other than that, looks nice!

**Review by Fobhep — APPROVED** [review]

**Pull request merged**
